//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetaliuComanda
    {
        public int DetaliuComandaId { get; set; }
        public int ComandaComandaId { get; set; }
        public int MecanicMecanicId { get; set; }
        public int MaterialMaterialId { get; set; }
        public int OperatieOperatieId { get; set; }
        public Nullable<int> ImagineImagineId { get; set; }
    
        public virtual Comanda Comanda { get; set; }
        public virtual Mecanic Mecanic { get; set; }
        public virtual Material Material { get; set; }
        public virtual Operatie Operatie { get; set; }
        public virtual Imagine Imagine { get; set; }
    }
}
