//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class DetaliuComanda
    {
        [DataMember]
        public int DetaliuComandaId { get; set; }
        [DataMember]
        public int ComandaComandaId { get; set; }
        [DataMember]
        public int MecanicMecanicId { get; set; }
        [DataMember]
        public int MaterialMaterialId { get; set; }
        [DataMember]
        public int OperatieOperatieId { get; set; }
        [DataMember]
        public Nullable<int> ImagineImagineId { get; set; }
        [DataMember]
        public virtual Comanda Comanda { get; set; }
        [DataMember]
        public virtual Mecanic Mecanic { get; set; }
        [DataMember]
        public virtual Material Material { get; set; }
        [DataMember]
        public virtual Operatie Operatie { get; set; }
        [DataMember]
        public virtual Imagine Imagine { get; set; }
    }
}
